//
// Generated file, do not edit! Created by opp_msgtool 6.0 from applications/ServerPacket.msg.
//

#ifndef __SERVERPACKET_M_H
#define __SERVERPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ServerPacket;
#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

/**
 * Class generated from <tt>applications/ServerPacket.msg:18</tt> by opp_msgtool.
 * <pre>
 * packet ServerPacket extends inet::Packet
 * {
 *     bool turnIrrigationOn;
 * }
 * </pre>
 */
class ServerPacket : public ::inet::Packet
{
  protected:
    bool turnIrrigationOn = false;

  private:
    void copy(const ServerPacket& other);

  protected:
    bool operator==(const ServerPacket&) = delete;

  public:
    ServerPacket(const char *name=nullptr, short kind=0);
    ServerPacket(const ServerPacket& other);
    virtual ~ServerPacket();
    ServerPacket& operator=(const ServerPacket& other);
    virtual ServerPacket *dup() const override {return new ServerPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getTurnIrrigationOn() const;
    virtual void setTurnIrrigationOn(bool turnIrrigationOn);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ServerPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ServerPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ServerPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<ServerPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SERVERPACKET_M_H

